subjects = [['ACCT','Accounting'],
	['AE','Aerospace Engineering'],
	['AFAS','Air Force Aerospace Studies'],
	['ANTH','Anthropology'],
	['ARCH','Archeology'],
	['ART','Art History'],
	['BIOL','Biology'],
	['BA','Business Administration'],
	['BCS','Business Computing Systems'],
	['CERT','Certifications'],
	['CH E','Chemical Engineering'],
	['CHEM','Chemistry'],
	['CE','Civil Engineering'],
	['COMM','Communication'],
	['CED','Community Education'],
	['SVC','Community Service'],
	['CSE','Computer Science &amp; Engineering'],
	['ERTH','Earth Science'],
	['ECON','Economics'],
	['EDUC','Education'],
	['EE','Electrical Engineering'],
	['ED','Engineering Design'],
	['EMGT','Engineering Management'],
	['EM','Engineering Mechanics'],
	['ES','Engineering Science'],
	['ENGL','English'],
	['ENVE','Environmental Engineering'],
	['ENVS','Environmental Science'],
	['EXCH','Exchange'],
	['EXPL','Explosives Engineering'],
	['FIN','Finance'],
	['FA','Fine Arts'],
	['FREN','French'],
	['GEOC','Geochemistry'],
	['GEOL','Geology'],
	['GEOP','Geophysics'],
	['GERM','German'],
	['HW','Health &amp; Wellness'],
	['HIST','History'],
	['HUMA','Humanities'],
	['HYD','Hydrology'],
	['IT','Information Technology'],
	['JAPN','Japanese'],
	['LANG','Language'],
	['LIFE','Lifestyle Activities'],
	['MGT','Management'],
	['MKT','Marketing'],
	['MATE','Materials Engineering'],
	['MATH','Mathematics'],
	['MENG','Mechanical Engineering'],
	['METE','Metallurgy'],
	['MS','Military Science'],
	['ME','Mineral Engineering'],
	['MUS','Music'],
	['OPT','Optics'],
	['PETR','Petroleum Engineering'],
	['PHIL','Philosophy'],
	['PR','Physical Recreation'],
	['PHYS','Physics'],
	['PS','Political Science'],
	['PSY','Psychology'],
	['ST','Science Teaching'],
	['SS','Social Science'],
	['SPAN','Spanish'],
	['TC','Technical Communication'],
	['THEA','Theater'],
	['WGS','Women's and Gender Studies']]